# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: ["development"]

jobs:
  test-and-merge-to-main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install deps
        run: npm ci
      - name: Run tests
        run: npm test

      - name: Merge development -> main
        uses: everlytic/branch-merge@1.1.2
        with:
          type: now
          target_branch: main
          source_ref: ${{ github.ref }}
          github_token: ${{ github.token }}
          commit_message_template: "[Automated] Merged bradevelopment into main"
